baseURL = "https://ragstorichescleaning.netlify.app/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Rags To Riches Cleaning"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Service"
url = "#service"
weight = 2
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3
[[menu.main]]
name = "History"
url = "#history"
weight = 4
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "About"
url = "#about"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About Us"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Posts"
url = "#blog"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Rags To Riches Cleaning 2022"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "1519 W Warren Blvd Chicago IL"
email = "info@ragstorichescleaning.netlify.app"
openingHours = "Mon - Sat 7am - 7pm"
phone = "(312) 838-0559"

[params.map]
APIkey = "API_TOKEN"
latitude = "41.882134"
longitude = "-87.6683181"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
