[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"


[[edge_functions]]
function = "geolocation"
path = "/test"

[functions]
  directory = "functions/"